### ISSUE TITLE
Manage Configuration file(*.yml) using submodule in git

### ISSUE THREAD

**Issue by mangchhe** [withDogecoin/chaterview#15]
### Discussed in https://github.com/withDogecoin/chaterview/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **mangchhe** April 29, 2023</sup>
## Summary

We can manage *.yml files using submodule
This method can manage the configuration files without external sharing.

## How

- Create private github repo
- Add *.yml files to the private github repo
- When building the project, copy the *.yml files copy into `/src/main/resources`
  - configure `build.gradle.ks`
  - copy *.yml files before executing the build task
</div>

**Comment by mangchhe** [comment]
@BAEKJungHo 
If you think it's a good idea, i'll work it

**Comment by BAEKJungHo** [comment]
@mangchhe Good!
