### ISSUE TITLE
`SpringDataHibernateMutinyReactiveQueryFactory` is not bean

### ISSUE THREAD

**Issue by mangchhe** [withDogecoin/chaterview#18]
When I ran the project, not found `SpringDataHibernateMutinyReactiveQueryFactory` bean

**Comment by BAEKJungHo** [comment]
### JPA Config

-[LocalContainerEntityManagerFactoryBean](https://www.baeldung.com/the-persistence-layer-with-spring-and-jpa)
- @EnableJpaRepositories
