### ISSUE TITLE
Refactor Answer API

### ISSUE THREAD

**Issue by mangchhe** [withDogecoin/chaterview#37]
# Refactor Answer API

- I will refactor the things that came up in the previous issue.
> Separated by package
> Prompt DB Search Improvement
> Add Mapper Class

**Comment by BAEKJungHo** [comment]
@mangchhe package refacatoring plz.

__AS-IS__

- dto
  - command
  - query

__TO-BE__
- command
- query

To constrain the name dto to the Presentation Layer or Client Call.
